/**
 * LoginVista.java
 * Adnana Catrinel Dragut
 * v1.0 28/03/2022.
 * 
 */

package vista;

import com.google.gson.Gson;
import control.Hospital;
import control.OyenteVista;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import modelo.clasesDTOs.UsuarioDTO;
import modelo.clasesProxys.ProxySanitario;
import modelo.clasesProxys.ProxyUsuario;
import org.apache.commons.codec.digest.DigestUtils;

/**
 * Clase que contiene los métodos para crear y gestionar 
 * los componentes y los eventos de la pantalla Login.
 * 
 */
public class LoginVista extends javax.swing.JFrame{
    private ProxyUsuario pxUsuario = null;
    private ProxySanitario pxSanitario = null;
    private Gson gson = null;
    private OyenteVista oyenteVista = null;
    private static final String EMAIL_PATTERN = "^(.+)@(.+)\\.[a-z]{2,}$";
    private String idConexion = null;

    
    /* Mensajes de Error */
    private String ERROR_LOGIN = 
            "No se ha podido iniciar sesión en el sistema.\n" + 
            "Vuelva a introducir las credenciales.";
    private String ERROR_SINTAXIS_EMAIL =  
            "Sintaxis de correo electrónico errónea.\n" +
            "Vuelva a introducir las credenciales.";
    private String ERROR_VERIFICACIÓN_USUARIO = 
        "El usuario no existe en el sistema.\n";
    
    /**
     * Crea e inicializa los componentes de LoginVista.
     */
    public LoginVista(OyenteVista _oyenteVista, ProxySanitario _pxSanitario, String _idConexion) {
        this.pxUsuario = new ProxyUsuario();
        this.pxSanitario = _pxSanitario;
        this.gson = new Gson();
        this.oyenteVista = _oyenteVista;
        this.idConexion = _idConexion;

        initComponents();
        //this.setVisible(true); // habilita la vista
        setResizable(false);  // deshabilita la opción de maximizar-minimizar 
        pack();   // ajusta ventana y sus componentes
        setLocationRelativeTo(null);  // centra en la pantalla
        b_Login.setEnabled(false);
        b_connecter.setText("Connected with id " + idConexion);
        b_connecter.setBackground(Color.green);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        panel_principal = new javax.swing.JPanel();
        panel_izqd = new javax.swing.JPanel();
        hospital_icon = new javax.swing.JLabel();
        hospital_label = new javax.swing.JLabel();
        management_label = new javax.swing.JLabel();
        system_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        pwd_label = new javax.swing.JLabel();
        correoSanitario = new javax.swing.JTextField();
        pwdSanitario = new javax.swing.JPasswordField();
        b_Login = new javax.swing.JButton();
        asterisco_label_email = new javax.swing.JLabel();
        asterisco_label_pwd = new javax.swing.JLabel();
        campo_obligatorio_label = new javax.swing.JLabel();
        b_connecter = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(51, 255, 204));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        panel_principal.setBackground(new java.awt.Color(255, 255, 255));

        panel_izqd.setBackground(new java.awt.Color(0, 153, 153));

        hospital_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imgs/hospital_icon.png"))); // NOI18N

        hospital_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        hospital_label.setText("HOSPITAL");

        management_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        management_label.setText("MANAGEMENT");

        system_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        system_label.setText("SYSTEM");

        javax.swing.GroupLayout panel_izqdLayout = new javax.swing.GroupLayout(panel_izqd);
        panel_izqd.setLayout(panel_izqdLayout);
        panel_izqdLayout.setHorizontalGroup(
            panel_izqdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_izqdLayout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addGroup(panel_izqdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(system_label)
                    .addComponent(management_label)
                    .addGroup(panel_izqdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_izqdLayout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(hospital_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(hospital_label, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        panel_izqdLayout.setVerticalGroup(
            panel_izqdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_izqdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hospital_icon)
                .addGap(18, 18, 18)
                .addComponent(hospital_label)
                .addGap(33, 33, 33)
                .addComponent(management_label)
                .addGap(28, 28, 28)
                .addComponent(system_label)
                .addGap(48, 48, 48))
        );

        email_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        email_label.setText("Email");

        pwd_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        pwd_label.setText("Contraseña");

        correoSanitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                correoSanitarioKeyTyped(evt);
            }
        });

        pwdSanitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwdSanitarioKeyTyped(evt);
            }
        });

        b_Login.setBackground(new java.awt.Color(204, 204, 204));
        b_Login.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        b_Login.setForeground(new java.awt.Color(0, 153, 153));
        b_Login.setText("Login");
        b_Login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_Login.setFocusable(false);
        b_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_LoginActionPerformed(evt);
            }
        });

        asterisco_label_email.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email.setText("*");

        asterisco_label_pwd.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_pwd.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_pwd.setText("*");

        campo_obligatorio_label.setFont(new java.awt.Font("Berlin Sans FB", 2, 13)); // NOI18N
        campo_obligatorio_label.setForeground(new java.awt.Color(255, 51, 0));
        campo_obligatorio_label.setText("* Campos obligatorios");

        b_connecter.setBackground(new java.awt.Color(204, 204, 204));
        b_connecter.setText("   ");
        b_connecter.setBorder(null);
        b_connecter.setFocusable(false);
        b_connecter.setSelected(true);

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addComponent(panel_izqd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(asterisco_label_email)
                                    .addComponent(asterisco_label_pwd))
                                .addGap(1, 1, 1)
                                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_principalLayout.createSequentialGroup()
                                        .addComponent(pwd_label, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pwdSanitario, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_principalLayout.createSequentialGroup()
                                        .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(correoSanitario, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 51, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_principalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b_Login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_obligatorio_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_principalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b_connecter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_izqd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addComponent(b_connecter)
                .addGap(66, 66, 66)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_label)
                    .addComponent(correoSanitario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwd_label)
                    .addComponent(pwdSanitario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campo_obligatorio_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    /**
     * Escribe mensaje con diálogo modal.
     * 
     * @param mensaje
     */    
    public void mensajeDialogo(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, 
            Hospital.TITULO + " " + Hospital.VERSION, 
            JOptionPane.ERROR_MESSAGE,  null);    
    } 
    
    /**
     * Comprueba que se han introducido valores en los campos del formulario,
     * y verifica que la sintaxis del email es correcta.
     * 
     * @param email
     * @param pwd
     * @return boolean
     */
    private boolean sintaxisCorreoCorrecta(String email){
        Pattern pattern = Pattern.compile(EMAIL_PATTERN);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }
    
    /**
     * Lee los datos del formulario y los envía al servidor,
     * si las credenciales son válidas habilita la siguiente 
     * pantalla en función del usuario que ha iniciado sesión.
     * 
     * @param evt 
     */
    private void b_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_LoginActionPerformed
        String email = "";
        String pwd = "";
        String usuarioJsonSended = null;
        String usuarioJsonReceived = null;
        UsuarioDTO usuario = null;
        
        email = correoSanitario.getText();
        pwd = String.valueOf(pwdSanitario.getPassword());
                
        if (! sintaxisCorreoCorrecta(email)){
            mensajeDialogo(ERROR_SINTAXIS_EMAIL);
            return;
        } else{         
            /* Se encripta la contraseña introducida por el usuario con algoritmo md5 */
            String encriptMD5_pwd = DigestUtils.md5Hex(pwd);
            
            usuario = new UsuarioDTO("180", email, encriptMD5_pwd);
            usuarioJsonSended = usuario.toJson();

            try {
                usuarioJsonReceived = pxUsuario.verificarUsuario(usuarioJsonSended); 
                System.out.println("Recibir:" + usuarioJsonReceived);
                if(usuarioJsonReceived != null){
                    usuario = gson.fromJson(usuarioJsonReceived, UsuarioDTO.class);
                    this.dispose();
                
                    if (usuario.isAdmin()){
                        new MenuAdminVista(oyenteVista, pxSanitario);
                    } else{
                        System.out.println("Es Sanitario");
                    }
                } else{
                    mensajeDialogo(ERROR_VERIFICACIÓN_USUARIO);
                }

            } catch (Exception ex) {
                mensajeDialogo(ERROR_LOGIN);
                ex.printStackTrace();
            } 
        }
    }//GEN-LAST:event_b_LoginActionPerformed

    private void changed(){
        if (correoSanitario.getText().isBlank() || 
                String.valueOf(pwdSanitario.getPassword()).isBlank()){
            b_Login.setEnabled(false);
        }
        else {
            b_Login.setEnabled(true);
        }
    }
    
    private void correoSanitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoSanitarioKeyTyped
        changed();
    }//GEN-LAST:event_correoSanitarioKeyTyped

    private void pwdSanitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdSanitarioKeyTyped
        changed();
    }//GEN-LAST:event_pwdSanitarioKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asterisco_label_email;
    private javax.swing.JLabel asterisco_label_pwd;
    private javax.swing.JButton b_Login;
    private javax.swing.JButton b_connecter;
    private javax.swing.JLabel campo_obligatorio_label;
    private javax.swing.JTextField correoSanitario;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel hospital_icon;
    private javax.swing.JLabel hospital_label;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel management_label;
    private javax.swing.JPanel panel_izqd;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JPasswordField pwdSanitario;
    private javax.swing.JLabel pwd_label;
    private javax.swing.JLabel system_label;
    // End of variables declaration//GEN-END:variables
}
