/**
 * NuevoSanitarioVista.java
 * Adnana Catrinel Dragut
 * v1.0 02/04/2022.
 * 
 */

package vista;

import com.google.gson.Gson;
import control.Hospital;
import control.OyenteVista;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JOptionPane;
import modelo.clasesDTOs.SanitarioDTO;
import modelo.clasesProxys.ProxySanitario;
import org.apache.commons.codec.digest.DigestUtils;

/**
 * Clase que contiene los métodos para crear y gestionar 
 * los componentes y los eventos de la pantalla NuevoSanitarioVista.
 * 
 */
public class NuevoSanitarioVista extends javax.swing.JFrame implements PropertyChangeListener{
    private MenuAdminVista menuAdminVista = null;
    private ProxySanitario pxSanitario = null;
    private Gson gson = null;
    private OyenteVista oyenteVista = null;
    
    /* Mensajes de Error */
    private String ERROR_DAR_ALTA_SANITARIO = 
            "No se ha podido dar de alta al sanitario.\n" + 
            "Vuelva a introducir los datos.";
    
    /**
     * Crea e inicializa los componentes de NuevoSanitarioVista.
     */
    public NuevoSanitarioVista(MenuAdminVista _menuAdminVista, OyenteVista _oyenteVista, ProxySanitario _pxSanitario) {
        this.menuAdminVista  = _menuAdminVista;
        this.pxSanitario = _pxSanitario;
        this.gson = new Gson();
        this.oyenteVista = _oyenteVista;
        pxSanitario.nuevoObservador(this);
                
        initComponents();
        this.setVisible(true); // habilita la vista
        setResizable(false);  //Deshabilita la opción de maximizar-minimizar 
        pack();   // ajusta ventana y sus componentes
        setLocationRelativeTo(null);  // centra en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        asterisco_label_email1 = new javax.swing.JLabel();
        panel_principal = new javax.swing.JPanel();
        paner_superior = new javax.swing.JPanel();
        nuevoSanitario_label = new javax.swing.JLabel();
        hospital_icon = new javax.swing.JLabel();
        datos_label = new javax.swing.JLabel();
        nombre_label = new javax.swing.JLabel();
        nombre_input_field = new javax.swing.JTextField();
        apellido1_label = new javax.swing.JLabel();
        apellido1_input_field = new javax.swing.JTextField();
        apellido2_label = new javax.swing.JLabel();
        apellido2_input_field = new javax.swing.JTextField();
        dni_label = new javax.swing.JLabel();
        dni_input_field = new javax.swing.JTextField();
        telefono_label = new javax.swing.JLabel();
        telefono_input_field = new javax.swing.JTextField();
        puesto_label = new javax.swing.JLabel();
        puesto_comboBox = new javax.swing.JComboBox<>();
        email_label = new javax.swing.JLabel();
        email_input_field = new javax.swing.JTextField();
        pwd_label = new javax.swing.JLabel();
        pwd_input_field = new javax.swing.JPasswordField();
        b_Cancelar = new javax.swing.JButton();
        b_Guardar = new javax.swing.JButton();
        asterisco_label_email = new javax.swing.JLabel();
        asterisco_label_email2 = new javax.swing.JLabel();
        asterisco_label_email3 = new javax.swing.JLabel();
        asterisco_label_email4 = new javax.swing.JLabel();
        asterisco_label_email5 = new javax.swing.JLabel();
        asterisco_label_email6 = new javax.swing.JLabel();
        asterisco_label_email7 = new javax.swing.JLabel();
        asterisco_label_email8 = new javax.swing.JLabel();
        campo_obligatorio_label = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jLabel5.setText("Email");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Login");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        asterisco_label_email1.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email1.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email1.setText("*");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_principal.setBackground(new java.awt.Color(255, 255, 255));
        panel_principal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel_principal.setPreferredSize(new java.awt.Dimension(630, 360));

        paner_superior.setBackground(new java.awt.Color(0, 153, 153));
        paner_superior.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        nuevoSanitario_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        nuevoSanitario_label.setText("Nuevo Sanitario");

        hospital_icon.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        hospital_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imgs/hospital_icon.png"))); // NOI18N
        hospital_icon.setMaximumSize(new java.awt.Dimension(70, 70));
        hospital_icon.setMinimumSize(new java.awt.Dimension(70, 70));
        hospital_icon.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout paner_superiorLayout = new javax.swing.GroupLayout(paner_superior);
        paner_superior.setLayout(paner_superiorLayout);
        paner_superiorLayout.setHorizontalGroup(
            paner_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paner_superiorLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(hospital_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(nuevoSanitario_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paner_superiorLayout.setVerticalGroup(
            paner_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hospital_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paner_superiorLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(nuevoSanitario_label)
                .addGap(28, 28, 28))
        );

        datos_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        datos_label.setForeground(new java.awt.Color(0, 153, 153));
        datos_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datos_label.setText("Datos");
        datos_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nombre_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        nombre_label.setText("Nombre");

        apellido1_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        apellido1_label.setText("1º. Apellido");

        apellido2_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        apellido2_label.setText("2º. Apellido");

        dni_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        dni_label.setText("DNI");

        telefono_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        telefono_label.setText("Teléfono");

        puesto_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        puesto_label.setText("Puesto");

        puesto_comboBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        puesto_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Médico", "Enfermero", "Especialista", "Auxiliar", "Otros" }));

        email_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        email_label.setText("Correo Electrónico");

        pwd_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        pwd_label.setText("Contraseña");

        b_Cancelar.setBackground(new java.awt.Color(204, 204, 204));
        b_Cancelar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        b_Cancelar.setForeground(new java.awt.Color(0, 153, 153));
        b_Cancelar.setText("Cancelar");
        b_Cancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_Cancelar.setFocusable(false);
        b_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CancelarActionPerformed(evt);
            }
        });

        b_Guardar.setBackground(new java.awt.Color(204, 204, 204));
        b_Guardar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        b_Guardar.setForeground(new java.awt.Color(0, 153, 153));
        b_Guardar.setText("Guardar");
        b_Guardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_Guardar.setFocusable(false);
        b_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_GuardarActionPerformed(evt);
            }
        });

        asterisco_label_email.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email.setText("*");

        asterisco_label_email2.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email2.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email2.setText("*");

        asterisco_label_email3.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email3.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email3.setText("*");

        asterisco_label_email4.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email4.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email4.setText("*");

        asterisco_label_email5.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email5.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email5.setText("*");

        asterisco_label_email6.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email6.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email6.setText("*");

        asterisco_label_email7.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email7.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email7.setText("*");

        asterisco_label_email8.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email8.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email8.setText("*");

        campo_obligatorio_label.setFont(new java.awt.Font("Berlin Sans FB", 2, 13)); // NOI18N
        campo_obligatorio_label.setForeground(new java.awt.Color(255, 51, 0));
        campo_obligatorio_label.setText("* Campos obligatorios");

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(datos_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(paner_superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(asterisco_label_email4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(asterisco_label_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(asterisco_label_email7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addComponent(email_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(email_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(asterisco_label_email8)
                                .addGap(6, 6, 6)
                                .addComponent(pwd_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pwd_input_field))
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel_principalLayout.createSequentialGroup()
                                        .addComponent(b_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(b_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_principalLayout.createSequentialGroup()
                                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panel_principalLayout.createSequentialGroup()
                                                .addComponent(dni_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dni_input_field))
                                            .addGroup(panel_principalLayout.createSequentialGroup()
                                                .addComponent(nombre_label, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nombre_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel_principalLayout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(asterisco_label_email2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panel_principalLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(asterisco_label_email5, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panel_principalLayout.createSequentialGroup()
                                                .addComponent(telefono_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(telefono_input_field)
                                                .addGap(18, 18, 18)
                                                .addComponent(asterisco_label_email6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(puesto_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(puesto_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panel_principalLayout.createSequentialGroup()
                                                .addComponent(apellido1_label)
                                                .addGap(18, 18, 18)
                                                .addComponent(apellido1_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(asterisco_label_email3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(apellido2_label)
                                                .addGap(10, 10, 10)
                                                .addComponent(apellido2_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 6, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_principalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(campo_obligatorio_label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addComponent(paner_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datos_label)
                .addGap(18, 18, 18)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_label)
                    .addComponent(apellido1_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido1_label)
                    .addComponent(nombre_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido2_label)
                    .addComponent(apellido2_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dni_label)
                    .addComponent(dni_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono_label)
                    .addComponent(telefono_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puesto_label)
                    .addComponent(puesto_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwd_label)
                    .addComponent(email_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_label)
                    .addComponent(asterisco_label_email7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_obligatorio_label)
                .addGap(18, 18, 18)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Escribe mensaje con diálogo modal.
     * 
     * @param mensaje
     */    
    public void mensajeDialogo(String mensaje, int messageType) {
        JOptionPane.showMessageDialog(this, mensaje, 
            Hospital.TITULO + " " + Hospital.VERSION, 
            messageType,  null);    
    } 
    
    private void b_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CancelarActionPerformed
        this.dispose();
        menuAdminVista.setVisible(true);
    }//GEN-LAST:event_b_CancelarActionPerformed
   
    private void b_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_GuardarActionPerformed
        String nombre = "";
        String apellido1 = "";
        String apellido2 = "";
        String dni = "";
        String telefono = "";
        String email = "";
        String pwd = "";
        String puestoTrabajo = "";
        String sanitarioJsonToSend=  null;
        SanitarioDTO sanitario = null;
        
        nombre = nombre_input_field.getText();
        apellido1 = apellido1_input_field.getText();
        apellido2 = apellido2_input_field.getText();
        dni = dni_input_field.getText();
        telefono = telefono_input_field.getText();
        email = email_input_field.getText();
        pwd = String.valueOf(pwd_input_field.getPassword());
        puestoTrabajo = String.valueOf(puesto_comboBox.getSelectedItem());
        
        /* Se encripta la contraseña introducida por el usuario con algoritmo md5 */
        String encriptMD5_pwd = DigestUtils.md5Hex(pwd);
        System.out.println(encriptMD5_pwd);
                
        sanitario = new SanitarioDTO(nombre, apellido1, apellido2, dni, Integer.parseInt(telefono), email, encriptMD5_pwd, puestoTrabajo);
        sanitarioJsonToSend = sanitario.toJson();
        System.out.println("1" + sanitarioJsonToSend);

        oyenteVista.eventoProducido(OyenteVista.Evento.DAR_ALTA_SANITARIO, sanitarioJsonToSend);
    }//GEN-LAST:event_b_GuardarActionPerformed

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(
                ProxySanitario.PROPIEDAD_DAR_ALTA_SANITARIO)) {
            pxSanitario.eliminarObservador(this);
            String sanitarioJsonToReceive = (String)evt.getNewValue();
            mensajeDialogo("Se ha dado de alta un nuevo sanitario.", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            SanitarioDTO sanitarioDTO = gson.fromJson(
                sanitarioJsonToReceive, SanitarioDTO.class);
            System.out.println(sanitarioDTO.toString());
            menuAdminVista.setVisible(true);
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido1_input_field;
    private javax.swing.JLabel apellido1_label;
    private javax.swing.JTextField apellido2_input_field;
    private javax.swing.JLabel apellido2_label;
    private javax.swing.JLabel asterisco_label_email;
    private javax.swing.JLabel asterisco_label_email1;
    private javax.swing.JLabel asterisco_label_email2;
    private javax.swing.JLabel asterisco_label_email3;
    private javax.swing.JLabel asterisco_label_email4;
    private javax.swing.JLabel asterisco_label_email5;
    private javax.swing.JLabel asterisco_label_email6;
    private javax.swing.JLabel asterisco_label_email7;
    private javax.swing.JLabel asterisco_label_email8;
    private javax.swing.JButton b_Cancelar;
    private javax.swing.JButton b_Guardar;
    private javax.swing.JLabel campo_obligatorio_label;
    private javax.swing.JLabel datos_label;
    private javax.swing.JTextField dni_input_field;
    private javax.swing.JLabel dni_label;
    private javax.swing.JTextField email_input_field;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel hospital_icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombre_input_field;
    private javax.swing.JLabel nombre_label;
    private javax.swing.JLabel nuevoSanitario_label;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JPanel paner_superior;
    private javax.swing.JComboBox<String> puesto_comboBox;
    private javax.swing.JLabel puesto_label;
    private javax.swing.JPasswordField pwd_input_field;
    private javax.swing.JLabel pwd_label;
    private javax.swing.JTextField telefono_input_field;
    private javax.swing.JLabel telefono_label;
    // End of variables declaration//GEN-END:variables

}
