/**
 * NuevoSanitarioVista.java
 * Adnana Catrinel Dragut
 * v1.0 02/04/2022.
 * 
 */

package vista;

import com.google.gson.Gson;
import control.Hospital;
import control.OyenteVista;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JOptionPane;
import modelo.clasesDTOs.SanitarioDTO;
import modelo.clasesProxys.ProxySanitario;
import org.apache.commons.codec.digest.DigestUtils;

/**
 * Clase que contiene los métodos para crear y gestionar 
 * los componentes y los eventos de la pantalla NuevoSanitarioVista.
 * 
 */
public class NuevoSanitarioVista extends javax.swing.JFrame implements PropertyChangeListener{
    private MenuAdminVista menuAdminVista = null;
    private ProxySanitario pxSanitario = null;
    private Gson gson = null;
    private OyenteVista oyenteVista = null;
    private String idConexion = null;
    
    /* Mensajes de Error */
    public final static String ERROR_DAR_ALTA_SANITARIO = 
            "No se ha podido realizar la operación para dar de alta un sanitario.\n" + 
            "Vuelva a introducir los datos.";
    
    /* Mensajes de Éxito */
    public final static String EXITO_DAR_ALTA_SANITARIO = 
            "Se ha dado de alta al sanitario con dni: ";
    
    /**
     * Crea e inicializa los componentes de NuevoSanitarioVista.
     * 
     */
    public NuevoSanitarioVista(MenuAdminVista _menuAdminVista, 
            OyenteVista _oyenteVista, ProxySanitario _pxSanitario, String _idConexion) {
        this.menuAdminVista  = _menuAdminVista;
        this.pxSanitario = _pxSanitario;
        this.gson = new Gson();
        this.oyenteVista = _oyenteVista;
        this.idConexion = _idConexion;
        pxSanitario.nuevoObservador(this);
                
        initComponents();
        setResizable(false);  //Deshabilita la opción de maximizar-minimizar 
        pack();   // ajusta ventana y sus componentes
        setLocationRelativeTo(null);  // centra en la pantalla
        habilitarBotonConectado(_idConexion);
                    
        b_Guardar.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        asterisco_label_email1 = new javax.swing.JLabel();
        panel_principal = new javax.swing.JPanel();
        paner_superior = new javax.swing.JPanel();
        nuevoSanitario_label = new javax.swing.JLabel();
        hospital_icon = new javax.swing.JLabel();
        b_connecter = new javax.swing.JButton();
        datos_label = new javax.swing.JLabel();
        nombre_label = new javax.swing.JLabel();
        nombre_input_field = new javax.swing.JTextField();
        apellido1_label = new javax.swing.JLabel();
        apellido1_input_field = new javax.swing.JTextField();
        apellido2_label = new javax.swing.JLabel();
        apellido2_input_field = new javax.swing.JTextField();
        dni_label = new javax.swing.JLabel();
        dni_input_field = new javax.swing.JTextField();
        telefono_label = new javax.swing.JLabel();
        telefono_input_field = new javax.swing.JTextField();
        puesto_label = new javax.swing.JLabel();
        puesto_comboBox = new javax.swing.JComboBox<>();
        email_label = new javax.swing.JLabel();
        email_input_field = new javax.swing.JTextField();
        pwd_label = new javax.swing.JLabel();
        pwd_input_field = new javax.swing.JPasswordField();
        b_Cancelar = new javax.swing.JButton();
        b_Guardar = new javax.swing.JButton();
        asterisco_label_email = new javax.swing.JLabel();
        asterisco_label_email2 = new javax.swing.JLabel();
        asterisco_label_email3 = new javax.swing.JLabel();
        asterisco_label_email4 = new javax.swing.JLabel();
        asterisco_label_email5 = new javax.swing.JLabel();
        asterisco_label_email6 = new javax.swing.JLabel();
        asterisco_label_email7 = new javax.swing.JLabel();
        asterisco_label_email8 = new javax.swing.JLabel();
        campo_obligatorio_label = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jLabel5.setText("Email");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Login");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        asterisco_label_email1.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email1.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email1.setText("*");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel_principal.setBackground(new java.awt.Color(255, 255, 255));
        panel_principal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel_principal.setPreferredSize(new java.awt.Dimension(630, 360));

        paner_superior.setBackground(new java.awt.Color(0, 153, 153));
        paner_superior.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        nuevoSanitario_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        nuevoSanitario_label.setText("Nuevo Sanitario");

        hospital_icon.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        hospital_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imgs/hospital_icon.png"))); // NOI18N
        hospital_icon.setMaximumSize(new java.awt.Dimension(70, 70));
        hospital_icon.setMinimumSize(new java.awt.Dimension(70, 70));
        hospital_icon.setPreferredSize(new java.awt.Dimension(70, 70));

        b_connecter.setBackground(new java.awt.Color(204, 204, 204));
        b_connecter.setText("   ");
        b_connecter.setBorder(null);
        b_connecter.setEnabled(false);
        b_connecter.setFocusable(false);
        b_connecter.setSelected(true);

        javax.swing.GroupLayout paner_superiorLayout = new javax.swing.GroupLayout(paner_superior);
        paner_superior.setLayout(paner_superiorLayout);
        paner_superiorLayout.setHorizontalGroup(
            paner_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paner_superiorLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(hospital_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(paner_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paner_superiorLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(nuevoSanitario_label)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paner_superiorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_connecter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        paner_superiorLayout.setVerticalGroup(
            paner_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hospital_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paner_superiorLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(nuevoSanitario_label)
                .addGap(11, 11, 11)
                .addComponent(b_connecter))
        );

        datos_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        datos_label.setForeground(new java.awt.Color(0, 153, 153));
        datos_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datos_label.setText("Datos");
        datos_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nombre_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        nombre_label.setText("Nombre");

        nombre_input_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_input_fieldKeyTyped(evt);
            }
        });

        apellido1_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        apellido1_label.setText("1º. Apellido");

        apellido1_input_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellido1_input_fieldKeyTyped(evt);
            }
        });

        apellido2_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        apellido2_label.setText("2º. Apellido");

        apellido2_input_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellido2_input_fieldKeyTyped(evt);
            }
        });

        dni_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        dni_label.setText("DNI");

        dni_input_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dni_input_fieldKeyTyped(evt);
            }
        });

        telefono_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        telefono_label.setText("Teléfono");

        telefono_input_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefono_input_fieldKeyTyped(evt);
            }
        });

        puesto_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        puesto_label.setText("Puesto");

        puesto_comboBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        puesto_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Médico", "Enfermero", "Especialista", "Auxiliar", "Otros" }));
        puesto_comboBox.setSelectedIndex(-1);
        puesto_comboBox.setToolTipText("");
        puesto_comboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                puesto_comboBoxPopupMenuWillBecomeVisible(evt);
            }
        });

        email_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        email_label.setText("Correo Electrónico");

        email_input_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                email_input_fieldKeyTyped(evt);
            }
        });

        pwd_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        pwd_label.setText("Contraseña");

        pwd_input_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwd_input_fieldKeyTyped(evt);
            }
        });

        b_Cancelar.setBackground(new java.awt.Color(204, 204, 204));
        b_Cancelar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        b_Cancelar.setForeground(new java.awt.Color(0, 153, 153));
        b_Cancelar.setText("Cancelar");
        b_Cancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_Cancelar.setFocusable(false);
        b_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CancelarActionPerformed(evt);
            }
        });

        b_Guardar.setBackground(new java.awt.Color(204, 204, 204));
        b_Guardar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        b_Guardar.setForeground(new java.awt.Color(0, 153, 153));
        b_Guardar.setText("Guardar");
        b_Guardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_Guardar.setFocusable(false);
        b_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_GuardarActionPerformed(evt);
            }
        });

        asterisco_label_email.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email.setText("*");

        asterisco_label_email2.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email2.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email2.setText("*");

        asterisco_label_email3.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email3.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email3.setText("*");

        asterisco_label_email4.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email4.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email4.setText("*");

        asterisco_label_email5.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email5.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email5.setText("*");

        asterisco_label_email6.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email6.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email6.setText("*");

        asterisco_label_email7.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email7.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email7.setText("*");

        asterisco_label_email8.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        asterisco_label_email8.setForeground(new java.awt.Color(255, 0, 0));
        asterisco_label_email8.setText("*");

        campo_obligatorio_label.setFont(new java.awt.Font("Berlin Sans FB", 2, 13)); // NOI18N
        campo_obligatorio_label.setForeground(new java.awt.Color(255, 51, 0));
        campo_obligatorio_label.setText("* Campos obligatorios");

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(datos_label)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(paner_superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(asterisco_label_email4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(asterisco_label_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(asterisco_label_email7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addComponent(email_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(email_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(asterisco_label_email8)
                                .addGap(6, 6, 6)
                                .addComponent(pwd_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pwd_input_field))
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel_principalLayout.createSequentialGroup()
                                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panel_principalLayout.createSequentialGroup()
                                                .addComponent(dni_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dni_input_field))
                                            .addGroup(panel_principalLayout.createSequentialGroup()
                                                .addComponent(nombre_label, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nombre_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel_principalLayout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(asterisco_label_email2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panel_principalLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(asterisco_label_email5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panel_principalLayout.createSequentialGroup()
                                                .addComponent(telefono_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(telefono_input_field)
                                                .addGap(18, 18, 18)
                                                .addComponent(asterisco_label_email6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(puesto_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(puesto_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panel_principalLayout.createSequentialGroup()
                                                .addComponent(apellido1_label)
                                                .addGap(18, 18, 18)
                                                .addComponent(apellido1_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(asterisco_label_email3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(apellido2_label)
                                                .addGap(10, 10, 10)
                                                .addComponent(apellido2_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(panel_principalLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(b_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(b_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 14, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_principalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(campo_obligatorio_label, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addComponent(paner_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datos_label)
                .addGap(18, 18, 18)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_label)
                    .addComponent(apellido1_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido1_label)
                    .addComponent(nombre_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido2_label)
                    .addComponent(apellido2_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dni_label)
                    .addComponent(dni_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono_label)
                    .addComponent(telefono_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puesto_label)
                    .addComponent(puesto_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwd_label)
                    .addComponent(email_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_label)
                    .addComponent(asterisco_label_email7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisco_label_email8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_obligatorio_label)
                .addGap(18, 18, 18)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    /**
     * Muestra un botón con el estado de la appCliente,
     * se mostrará el color verde si la conexión con el servidor
     * ha sido exitosa o el color amarillo en caso contrario. 
     * 
     * @param _idConexion 
     */
    private void habilitarBotonConectado(String _idConexion){
        if (idConexion.equals("0")){
            b_connecter.setEnabled(false);
            b_connecter.setText("Disconnected");
            b_connecter.setBackground(Color.YELLOW);
        } else{
            b_connecter.setEnabled(true);
            b_connecter.setText("Connected with id " + _idConexion);
            b_connecter.setBackground(Color.GREEN);
        }
    }
    
    /**
     * Escribe mensaje con diálogo modal.
     * 
     * @param mensaje
     */    
    public void mensajeDialogo(String mensaje, int messageType) {
        JOptionPane.showMessageDialog(this, mensaje, 
            Hospital.TITULO + " " + Hospital.VERSION, 
            messageType,  null);    
    } 
    
    /**
     * Cierra la ventana actual y regresa a la ventana MenuAdminVista
     * 
     * @param evt 
     */
    private void b_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CancelarActionPerformed
        this.dispose();
        menuAdminVista.setVisible(true);
    }//GEN-LAST:event_b_CancelarActionPerformed
   
    /**
     * Captura la información de los campos rellenados por el usuario y
     * crea el json del sanitario nuevo con dicha información
     * 
     * @return String
     */
    private String crearJsonSanitarioNuevo(){
        String nombre = nombre_input_field.getText();
        String apellido1 = apellido1_input_field.getText();
        String apellido2 = apellido2_input_field.getText();
        String dni = dni_input_field.getText();
        String telefono = telefono_input_field.getText();
        String email = email_input_field.getText();
        String pwd = String.valueOf(pwd_input_field.getPassword());
        String puestoTrabajo = String.valueOf(puesto_comboBox.getSelectedItem());
        
        /* Se encripta la contraseña introducida por el usuario con algoritmo md5 */
        String encriptMD5_pwd = DigestUtils.md5Hex(pwd);
                
        SanitarioDTO sanitario = new SanitarioDTO(nombre, apellido1, apellido2, 
            dni, Integer.parseInt(telefono), email, encriptMD5_pwd, puestoTrabajo);
        
        return sanitario.toJson();
    }
    
    /**
     * Envía la solicitud para dar de alta un sanitario a la capa control
     * 
     * @param evt 
     */
    private void b_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_GuardarActionPerformed
        String sanitarioJsonToSend = crearJsonSanitarioNuevo();
        
        if (sanitarioJsonToSend != null){
            oyenteVista.eventoProducido(OyenteVista.Evento.DAR_ALTA_SANITARIO, sanitarioJsonToSend);
        } else{
            mensajeDialogo(ERROR_DAR_ALTA_SANITARIO, JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_b_GuardarActionPerformed

    /**
     * Captura el evento relacionado con el cierre de la ventana, y 
     * envía el evento a la capa control para realizar las acciones
     * de finalización necesarias para la appCliente.
     * 
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        oyenteVista.eventoProducido(OyenteVista.Evento.SALIR, null);
    }//GEN-LAST:event_formWindowClosing

    /**
     * Habilita el botón de Guardar si todos los campos 
     * han sido completados y no poseen solo valores en blanco.
     */
    private void changed(){
        if (nombre_input_field.getText().isBlank() || 
                apellido1_input_field.getText().isBlank() ||
                apellido2_input_field.getText().isBlank() ||
                dni_input_field.getText().isBlank() || 
                telefono_input_field.getText().isBlank() ||
                puesto_comboBox.getSelectedItem() == null ||
                email_input_field.getText().isBlank() ||
                String.valueOf(pwd_input_field.getPassword()).isBlank()){
  
            b_Guardar.setEnabled(false);
        }
        else {
            b_Guardar.setEnabled(true);
        }
    }
    
    /**
     * Captura los eventos relacionados con la modificación del campo "nombre".
     * 
     */
    private void nombre_input_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_input_fieldKeyTyped
        changed();
    }//GEN-LAST:event_nombre_input_fieldKeyTyped

    /**
     * Captura los eventos relacionados con la modificación del campo "apellido1".
     * 
     */
    private void apellido1_input_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellido1_input_fieldKeyTyped
        changed();
    }//GEN-LAST:event_apellido1_input_fieldKeyTyped

    /**
     * Captura los eventos relacionados con la modificación del campo "apellido2".
     * 
     */
    private void apellido2_input_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellido2_input_fieldKeyTyped
        changed();
    }//GEN-LAST:event_apellido2_input_fieldKeyTyped

    /**
     * Captura los eventos relacionados con la modificación del campo "dni".
     * 
     */
    private void dni_input_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dni_input_fieldKeyTyped
        changed();
    }//GEN-LAST:event_dni_input_fieldKeyTyped

    /**
     * Captura los eventos relacionados con la modificación del campo "telefono".
     * 
     */
    private void telefono_input_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefono_input_fieldKeyTyped
        changed();
    }//GEN-LAST:event_telefono_input_fieldKeyTyped

    /**
     * Captura los eventos relacionados con la modificación del campo "puesto".
     * 
     */
    private void puesto_comboBoxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_puesto_comboBoxPopupMenuWillBecomeVisible
        changed();
    }//GEN-LAST:event_puesto_comboBoxPopupMenuWillBecomeVisible

    /**
     * Captura los eventos relacionados con la modificación del campo "correo".
     * 
     */
    private void email_input_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_input_fieldKeyTyped
        changed();
    }//GEN-LAST:event_email_input_fieldKeyTyped

    /**
     * Captura los eventos relacionados con la modificación del campo "contraseña".
     * 
     */
    private void pwd_input_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwd_input_fieldKeyTyped
        changed();
    }//GEN-LAST:event_pwd_input_fieldKeyTyped
    
    /**
     * Recibe evento dar alta sanitario
     * 
     * @param evt 
     */
    private void propiedadDarAltaSanitario(PropertyChangeEvent evt){
        String sanitarioJsonToReceive = (String)evt.getNewValue();
        SanitarioDTO sanitarioDTOReceived = gson.fromJson(
           sanitarioJsonToReceive, SanitarioDTO.class);

        mensajeDialogo(EXITO_DAR_ALTA_SANITARIO + 
           sanitarioDTOReceived.getDni(), JOptionPane.INFORMATION_MESSAGE);

        pxSanitario.eliminarObservador(this);
        this.dispose();
        menuAdminVista.setVisible(true);      
    }
    
    /**
     * Sobreescribe propertyChange para recibir cambios de modelo.
     * 
     * @param evt 
     */
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(
                ProxySanitario.PROPIEDAD_DAR_ALTA_SANITARIO)) {
            
            propiedadDarAltaSanitario(evt);
        } 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido1_input_field;
    private javax.swing.JLabel apellido1_label;
    private javax.swing.JTextField apellido2_input_field;
    private javax.swing.JLabel apellido2_label;
    private javax.swing.JLabel asterisco_label_email;
    private javax.swing.JLabel asterisco_label_email1;
    private javax.swing.JLabel asterisco_label_email2;
    private javax.swing.JLabel asterisco_label_email3;
    private javax.swing.JLabel asterisco_label_email4;
    private javax.swing.JLabel asterisco_label_email5;
    private javax.swing.JLabel asterisco_label_email6;
    private javax.swing.JLabel asterisco_label_email7;
    private javax.swing.JLabel asterisco_label_email8;
    private javax.swing.JButton b_Cancelar;
    private javax.swing.JButton b_Guardar;
    private javax.swing.JButton b_connecter;
    private javax.swing.JLabel campo_obligatorio_label;
    private javax.swing.JLabel datos_label;
    private javax.swing.JTextField dni_input_field;
    private javax.swing.JLabel dni_label;
    private javax.swing.JTextField email_input_field;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel hospital_icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombre_input_field;
    private javax.swing.JLabel nombre_label;
    private javax.swing.JLabel nuevoSanitario_label;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JPanel paner_superior;
    private javax.swing.JComboBox<String> puesto_comboBox;
    private javax.swing.JLabel puesto_label;
    private javax.swing.JPasswordField pwd_input_field;
    private javax.swing.JLabel pwd_label;
    private javax.swing.JTextField telefono_input_field;
    private javax.swing.JLabel telefono_label;
    // End of variables declaration//GEN-END:variables
}
