/**
 * WelcomeVista.java
 * Adnana Catrinel Dragut
 * v1.0 04/04/2022.
 * 
 */

package vista;

import control.Hospital;
import control.OyenteVista;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JOptionPane;
import modelo.clasesProxys.Comms;
import modelo.clasesProxys.ProxySanitario;

/**
 * Clase que contiene los métodos para crear y gestionar 
 * los componentes y los eventos de la pantalla de bienvenida.
 * 
 */
public class WelcomeVista extends javax.swing.JFrame implements PropertyChangeListener {
    private Comms comms = null;
    private ProxySanitario pxSanitario = null;
    private OyenteVista oyenteVista = null;
    private String idConexion = null;
    
    private static final int NUMERO_BARRA_PROGRESO = 100;
    private static final int MILISEGUNDOS_ESPERA_BARRA_PROGRESO = 40;

    /* Mensajes de Error */
    private String ERROR_CARGA_PAGINA_BIENVENIDA = 
            "No se ha podido cargar la página de bienvenida.";
    
    /**
     * Crea e inicializa los componentes de WelcomeVista.
     */
    public WelcomeVista(OyenteVista _oyenteVista, Comms _comms, ProxySanitario _pxSanitario) {
        this.comms = _comms;
        this.pxSanitario = _pxSanitario;
        this.oyenteVista = _oyenteVista;
        
        comms.nuevoObservador(this);
        initComponents();
        this.setVisible(true); // habilita la vista
        setResizable(false);  // deshabilita la opción de maximizar-minimizar 
        pack();   // ajusta ventana y sus componentes
        setLocationRelativeTo(null);  // centra en la pantalla
        crearProgressBar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_principal = new javax.swing.JPanel();
        hospital_icon = new javax.swing.JLabel();
        hospital_management_system_label = new javax.swing.JLabel();
        conectando_label = new javax.swing.JLabel();
        progress_bar = new javax.swing.JProgressBar();
        progress_bar_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_principal.setBackground(new java.awt.Color(0, 153, 153));

        hospital_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imgs/hospital_icon.png"))); // NOI18N

        hospital_management_system_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        hospital_management_system_label.setText("Hospital Management System");

        conectando_label.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        conectando_label.setText("Conectando con servidor...");

        progress_bar.setBackground(new java.awt.Color(255, 255, 255));

        progress_bar_label.setBackground(new java.awt.Color(255, 255, 255));
        progress_bar_label.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        progress_bar_label.setForeground(new java.awt.Color(255, 255, 255));
        progress_bar_label.setText("0%");

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(hospital_icon))
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conectando_label)
                            .addComponent(progress_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(hospital_management_system_label))
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(progress_bar_label)))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(hospital_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(hospital_management_system_label)
                .addGap(19, 19, 19)
                .addComponent(conectando_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress_bar_label)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(409, 275));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Escribe mensaje con diálogo modal.
     * 
     * @param mensaje
     */    
    public void mensajeDialogo(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, 
            Hospital.TITULO + " " + Hospital.VERSION, 
            JOptionPane.ERROR_MESSAGE,  null);    
    } 
    
    /**
     * Crea la barra de progreso. 
     * 
     */
    private void crearProgressBar(){
        for (int i=0; i < NUMERO_BARRA_PROGRESO; i++){
            try {
                Thread.sleep(MILISEGUNDOS_ESPERA_BARRA_PROGRESO);
                progress_bar_label.setText(i + "%");
                progress_bar.setValue(i);
            } catch (InterruptedException ex) {
                mensajeDialogo(ERROR_CARGA_PAGINA_BIENVENIDA);
            }
        }
    }
    
    /**
     * Recibe evento conectar
     * 
     * @param evt 
     */
    private void propiedadConectar(PropertyChangeEvent evt){
        String idConexion = (String)evt.getNewValue();

        if (idConexion == null){
            idConexion = "0"; 
        } 

        comms.eliminarObservador(this);
        this.dispose();
        new LoginVista(oyenteVista, comms, pxSanitario, idConexion).setVisible(true);  
    }
    
    /**
     * Sobreescribe propertyChange para recibir cambios de modelo.
     * 
     * @param evt 
     */
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(
                Comms.PROPIEDAD_CONECTADO)) {
            
            propiedadConectar(evt);
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conectando_label;
    private javax.swing.JLabel hospital_icon;
    private javax.swing.JLabel hospital_management_system_label;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JProgressBar progress_bar;
    private javax.swing.JLabel progress_bar_label;
    // End of variables declaration//GEN-END:variables
}
