CREATE TABLE PACIENTE (
	nss VARCHAR(255) PRIMARY KEY,
	nombre VARCHAR(255) NOT NULL,
   	apellido1 VARCHAR(255) NOT NULL,
	apellido2 VARCHAR(255) NOT NULL,
	alergias VARCHAR(255) NOT NULL,
	edad INT NOT NULL,
	altura DECIMAL NOT NULL,
	peso DECIMAL NOT NULL
);

CREATE TABLE MEDICAMENTO_PACIENTE (
	id INT AUTO_INCREMENT,
	fecha_inicio DATE NOT NULL,
   	fecha_fin DATE NOT NULL,
	nss_pac VARCHAR(255),
	codigo_medic INT NOT NULL,

	FOREIGN KEY (nss_pac)
	REFERENCES PACIENTE(nss)
	ON DELETE CASCADE,

	PRIMARY KEY(id, codigo_medic),

	FOREIGN KEY (codigo_medic)
	REFERENCES MEDICAMENTO(codigo)
	ON DELETE CASCADE
);

CREATE TABLE VACUNA_PACIENTE (
	id INT AUTO_INCREMENT,
	fecha DATE NOT NULL,
	nss_pac VARCHAR(255),
	codigo_vacuna INT NOT NULL,

	FOREIGN KEY (nss_pac)
	REFERENCES PACIENTE(nss)
	ON DELETE CASCADE,

	PRIMARY KEY(id, codigo_vacuna),

	FOREIGN KEY (codigo_vacuna)
	REFERENCES VACUNA(codigo)
	ON DELETE CASCADE
);

CREATE TABLE EPISODIO_DE_ATENCION (
	id INT AUTO_INCREMENT,
	fecha DATE NOT NULL,
	motivo VARCHAR(255) NOT NULL,
	diagnostico VARCHAR(255),
	nss_pac VARCHAR(255),

	FOREIGN KEY (nss_pac)
	REFERENCES PACIENTE(nss)
	ON DELETE CASCADE,

	PRIMARY KEY(id, nss_pac)
);

CREATE TABLE USUARIO (
    dni VARCHAR(255) PRIMARY KEY,
    correo VARCHAR(255) NOT NULL,
	contraseña VARCHAR(255) NOT NULL
);

CREATE TABLE ADMINISTRADOR (
    dni VARCHAR(255) PRIMARY KEY,
    
    FOREIGN KEY (dni)
	REFERENCES USUARIO(dni)
	ON DELETE CASCADE
);

CREATE TABLE SANITARIO (
	dni VARCHAR(255) PRIMARY KEY,
	nombre VARCHAR(255) NOT NULL,
   	apellido1 VARCHAR(255) NOT NULL,
	apellido2 VARCHAR(255) NOT NULL,
	telefono INT NOT NULL,
    
    FOREIGN KEY (dni)
	REFERENCES USUARIO(dni)
	ON DELETE CASCADE
);

CREATE TABLE CITA (
	codigo INT PRIMARY KEY AUTO_INCREMENT,
	descripcion VARCHAR(255) NOT NULL,
   	sala VARCHAR(255) NOT NULL,
	centro VARCHAR(255) NOT NULL,
	localidad VARCHAR(255) NOT NULL,
	hora DECIMAL NOT NULL,
	fecha DATE NOT NULL,
	nss_pac VARCHAR(255),
	dni_sanit VARCHAR(255),

	FOREIGN KEY (nss_pac)
	REFERENCES PACIENTE(nss)
	ON DELETE CASCADE,

	FOREIGN KEY (dni_sanit)
	REFERENCES SANITARIO(dni)
	ON DELETE CASCADE
);
